platform: Any CPU
version: 8.0.0.{build}
configuration: Debug
image: Visual Studio 2019

before_build:
- nuget restore CodeConverter.sln

build:
  project: CodeConverter.sln

test:
  assemblies:
    - 'Tests\bin\%configuration%\ICSharpCode.CodeConverter.Tests.dll'

artifacts:
  - path: 'Vsix\bin\%configuration%\ICSharpCode.CodeConverter.VsExtension.vsix'
